apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-app
  template:
    metadata:
      labels:
        app: anime-app
    spec:
      containers:
      - name: ml-app-container
        image: gcr.io/alpine-proton-467708-f6/ml-anime-project:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
spec:
  type: LoadBalancer
  selector:
    app: anime-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
